In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from sklearn.preprocessing import StandardScaler

In [2]:
df=pd.read_csv(r"D:\JAIMIN\Data Science\Machine Learning\advertising.csv")

In [3]:
df.isnull().sum()

TV           0
Radio        0
Newspaper    0
Sales        0
dtype: int64

In [4]:
df.duplicated().sum()

0

In [5]:
df.describe()

TV       Radio   Newspaper       Sales
count  200.000000  200.000000  200.000000  200.000000
mean   147.042500   23.264000   30.554000   15.130500
std     85.854236   14.846809   21.778621    5.283892
min      0.700000    0.000000    0.300000    1.600000
25%     74.375000    9.975000   12.750000   11.000000
50%    149.750000   22.900000   25.750000   16.000000
75%    218.825000   36.525000   45.100000   19.050000
max    296.400000   49.600000  114.000000   27.000000

In [6]:
df

TV  Radio  Newspaper  Sales
0    230.1   37.8       69.2   22.1
1     44.5   39.3       45.1   10.4
2     17.2   45.9       69.3   12.0
3    151.5   41.3       58.5   16.5
4    180.8   10.8       58.4   17.9
..     ...    ...        ...    ...
195   38.2    3.7       13.8    7.6
196   94.2    4.9        8.1   14.0
197  177.0    9.3        6.4   14.8
198  283.6   42.0       66.2   25.5
199  232.1    8.6        8.7   18.4

[200 rows x 4 columns]

In [7]:
df.columns

Index(['TV', 'Radio', 'Newspaper', 'Sales'], dtype='object')

In [8]:
y = df[['Sales']]
y.head()

Sales
0   22.1
1   10.4
2   12.0
3   16.5
4   17.9

In [9]:
x =df.drop(columns =["Sales"])
x

TV  Radio  Newspaper
0    230.1   37.8       69.2
1     44.5   39.3       45.1
2     17.2   45.9       69.3
3    151.5   41.3       58.5
4    180.8   10.8       58.4
..     ...    ...        ...
195   38.2    3.7       13.8
196   94.2    4.9        8.1
197  177.0    9.3        6.4
198  283.6   42.0       66.2
199  232.1    8.6        8.7

[200 rows x 3 columns]

In [10]:
scaler = StandardScaler()

In [11]:
arr=scaler.fit_transform(x)

In [12]:
arr

array([[ 9.69852266e-01,  9.81522472e-01,  1.77894547e+00],
       [-1.19737623e+00,  1.08280781e+00,  6.69578760e-01],
       [-1.51615499e+00,  1.52846331e+00,  1.78354865e+00],
       [ 5.20496822e-02,  1.21785493e+00,  1.28640506e+00],
       [ 3.94182198e-01, -8.41613655e-01,  1.28180188e+00],
       [-1.61540845e+00,  1.73103399e+00,  2.04592999e+00],
       [-1.04557682e+00,  6.43904671e-01, -3.24708413e-01],
       [-3.13436589e-01, -2.47406325e-01, -8.72486994e-01],
       [-1.61657614e+00, -1.42906863e+00, -1.36042422e+00],
       [ 6.16042873e-01, -1.39530685e+00, -4.30581584e-01],
       [-9.45155670e-01, -1.17923146e+00, -2.92486143e-01],
       [ 7.90028350e-01,  4.96973404e-02, -1.22232878e+00],
       [-1.43908760e+00,  7.99208859e-01,  1.62704048e+00],
       [-5.78501712e-01, -1.05768905e+00, -1.07502697e+00],
       [ 6.66253447e-01,  6.50657027e-01,  7.11007392e-01],
       [ 5.64664612e-01,  1.65000572e+00,  1.02862691e+00],
       [-9.25304978e-01,  9.00494200e-01

In [13]:
df1=pd.DataFrame(arr)

In [14]:
df1.head(10)

0         1         2
0  0.969852  0.981522  1.778945
1 -1.197376  1.082808  0.669579
2 -1.516155  1.528463  1.783549
3  0.052050  1.217855  1.286405
4  0.394182 -0.841614  1.281802
5 -1.615408  1.731034  2.045930
6 -1.045577  0.643905 -0.324708
7 -0.313437 -0.247406 -0.872487
8 -1.616576 -1.429069 -1.360424
9  0.616043 -1.395307 -0.430582

In [15]:
df1.describe()

0             1             2
count  2.000000e+02  2.000000e+02  2.000000e+02
mean   1.221245e-16 -4.529710e-16  2.220446e-16
std    1.002509e+00  1.002509e+00  1.002509e+00
min   -1.708823e+00 -1.570868e+00 -1.392646e+00
25%   -8.485295e-01 -8.973206e-01 -8.195504e-01
50%    3.161515e-02 -2.457858e-02 -2.211368e-01
75%    8.381955e-01  8.954299e-01  6.695788e-01
max    1.744029e+00  1.778300e+00  3.841171e+00

In [16]:
df.shape

(200, 4)

In [17]:
from sklearn.model_selection import train_test_split

In [18]:
x_train, x_test, y_train, y_test = train_test_split(
    arr, y, test_size=0.30, random_state=42)

In [19]:
x_train

array([[ 1.60273904, -0.85511837, -1.11185242],
       [ 0.4420574 , -0.15287334, -0.39375613],
       [-0.3986778 , -0.39595816,  0.37037197],
       [-1.4390876 ,  0.79920886,  1.62704048],
       [ 1.67747105, -1.29402151, -1.01518562],
       [-1.49046586, -0.49049114, -0.37994659],
       [ 1.711334  ,  0.29953451, -1.32359877],
       [-1.49863967, -0.75383303, -0.32931159],
       [-0.14879261, -1.24000266, -0.97836017],
       [-1.41806922,  1.06255074, -0.97836017],
       [-0.54463877, -0.92264193, -1.2407415 ],
       [-0.7805117 , -1.57086811, -0.98296335],
       [ 0.48292647, -0.34869167, -0.2280416 ],
       [ 0.34981006,  0.68441881,  0.37497515],
       [-0.24921376,  0.92075127,  2.2392636 ],
       [ 0.73047627, -0.17988276, -0.91391563],
       [-0.04837147,  0.40757221, -0.82645518],
       [ 0.4420574 ,  1.39341619, -1.32820195],
       [ 0.87994031, -1.2805168 ,  0.88592828],
       [ 1.10530405,  0.99502718, -0.33851796],
       [-1.51615499,  1.52846331,  1.783

In [20]:
from sklearn.linear_model import LinearRegression
lr=LinearRegression()

In [21]:
lr.fit(x_train,y_train)

LinearRegression()

In [22]:
lr.predict([[230.1,37.8,69.2]])

array([[1140.67262285]])

In [23]:
test1=scaler.transform([[230.1,37.8,69.2]])

D:\ANACONDA\anaconda3\Lib\site-packages\sklearn\base.py:464: UserWarning: X does not have valid feature names, but StandardScaler was fitted with feature names
  warnings.warn(


In [24]:
test1

array([[0.96985227, 0.98152247, 1.77894547]])

In [25]:
import pickle

In [26]:
import pickle
pickle.dump(lr,open('advertising_model.pickle', 'wb'))

In [27]:
%ls # linux command

 Volume in drive C is OS
 Volume Serial Number is E077-265C

 Directory of C:\Users\Jaimin Shah\Data Science


 Directory of C:\Users\Jaimin Shah\Data Science


 Directory of C:\Users\Jaimin Shah\Data Science



File Not Found


In [28]:
model=pickle.load((open('advertising_model.pickle','rb')))

In [29]:
model

LinearRegression()

In [30]:
df.head()

TV  Radio  Newspaper  Sales
0  230.1   37.8       69.2   22.1
1   44.5   39.3       45.1   10.4
2   17.2   45.9       69.3   12.0
3  151.5   41.3       58.5   16.5
4  180.8   10.8       58.4   17.9

In [31]:
test1

array([[0.96985227, 0.98152247, 1.77894547]])

In [32]:
test1=scaler.transform([[230.1,37.8,69.2]]) # Also do for remaining data from table

D:\ANACONDA\anaconda3\Lib\site-packages\sklearn\base.py:464: UserWarning: X does not have valid feature names, but StandardScaler was fitted with feature names
  warnings.warn(


In [33]:
model.predict(test1)

array([[21.5057118]])

In [34]:
test2=scaler.transform([[44.5,39.3,45.1]])

D:\ANACONDA\anaconda3\Lib\site-packages\sklearn\base.py:464: UserWarning: X does not have valid feature names, but StandardScaler was fitted with feature names
  warnings.warn(


In [35]:
model.predict(test2)

array([[11.52255765]])

In [36]:
lr.score(x_test,y_test)

0.9091484341849798

In [37]:
lr.score(x_train,y_train)

0.8919647339302077

In [38]:
base_preds=lr.predict(x_test)
base_preds

array([[17.15991908],
       [20.53369503],
       [23.68914396],
       [ 9.5191455 ],
       [21.60736836],
       [12.78101318],
       [21.08636345],
       [ 8.76054246],
       [17.11499951],
       [16.68789636],
       [ 8.97584663],
       [ 8.57645026],
       [18.33212325],
       [ 8.17863567],
       [12.64605571],
       [14.94486946],
       [ 8.34939536],
       [17.83858948],
       [11.12172174],
       [20.37740648],
       [20.9483297 ],
       [13.04035779],
       [11.01360656],
       [22.51142595],
       [ 9.40369784],
       [ 7.98591291],
       [20.86943368],
       [13.77882255],
       [10.83407064],
       [ 8.00419229],
       [15.88597618],
       [10.7027424 ],
       [20.9521718 ],
       [10.84679243],
       [21.50720813],
       [21.07347295],
       [12.22673775],
       [22.85273767],
       [12.57698182],
       [ 6.54597206],
       [11.93411853],
       [15.23490068],
       [10.07411153],
       [ 9.52159696],
       [17.11786382],
       [ 7

In [39]:
from sklearn.metrics import mean_absolute_error, mean_squared_error

In [40]:
mean_absolute_error(y_test,base_preds)

1.1594875061090586

In [41]:
np.sqrt(mean_squared_error(y_test,base_preds))

1.5942471691143598

In [42]:
y_test.mean()

Sales    13.61
dtype: float64

In [43]:
# Create adjusted r-squared function, this def formulation is applied to all types for r-squared
def adj_r2(x,y):
    r2=lr.score(x,y)
    n=x.shape[0]
    p=x.shape[1]
    adjusted_r2=1-(1-r2)*(n-1)/(n-p-1)
    return adjusted_r2

In [44]:
adj_r2(x_test,y_test)

0.904281386016318

In [45]:
lr.coef_

array([[4.58929971, 1.52105084, 0.17230839]])

In [46]:
lr.intercept_

array([15.25529627])

In [47]:
from sklearn.linear_model import Ridge, Lasso, RidgeCV, LassoCV, ElasticNet, ElasticNetCV, LinearRegression

In [48]:
# Liner Regression with LASSO
lassocv = LassoCV(cv=10, max_iter=200000)
lassocv.fit(x_train,y_train)

D:\ANACONDA\anaconda3\Lib\site-packages\sklearn\linear_model\_coordinate_descent.py:1563: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


LassoCV(cv=10, max_iter=200000)

In [49]:
lassocv.alpha_

0.004474995985544099

In [50]:
lasso = Lasso(alpha=lassocv.alpha_)
lasso.fit(x_train,y_train)

Lasso(alpha=0.004474995985544099)

In [51]:
lasso.score(x_test,y_test)

0.9091762786130346

In [52]:
y_pred = lassocv.predict(x_test)

In [53]:
mean_absolute_error(y_test,y_pred)

1.1584992166989372

In [54]:
np.sqrt(mean_squared_error(y_test,y_pred))

1.594002845849344

In [55]:
y_test.mean()

Sales    13.61
dtype: float64

In [56]:
# Create Linear Regression with Ridge
ridgecv = RidgeCV(alphas=np.random.uniform(0,10,50), cv=10)
ridgecv.fit(x_train,y_train)

RidgeCV(alphas=array([5.77606243, 7.62022668, 1.53947014, 6.93128784, 6.90878378,
       9.10869049, 1.94280876, 7.90358542, 3.15147532, 9.41889294,
       3.30471825, 0.85140544, 5.22936854, 0.01346779, 4.59164373,
       1.03329172, 3.46594216, 2.95387873, 6.99056945, 5.78382867,
       1.87248679, 1.19816802, 3.83096704, 6.12565194, 3.70225683,
       9.45334295, 6.67540398, 3.58792701, 9.67175409, 3.66225601,
       4.32632197, 1.68492556, 8.71182297, 2.86366232, 3.12519449,
       0.88788191, 8.94233631, 1.32821795, 5.67521048, 8.3947795 ,
       5.50546802, 7.25137987, 5.83270964, 9.90328593, 6.98143177,
       5.57675106, 2.65808756, 2.84315946, 8.60557494, 4.00631614]),
        cv=10)

In [57]:
ridgecv.alpha_

1.5394701351272233

In [58]:
ridge_lr=Ridge(alpha=ridgecv.alpha_)
ridge_lr.fit(x_train,y_train)

Ridge(alpha=1.5394701351272233)

In [59]:
y_pred = ridge_lr.predict(x_test)

In [60]:
mean_absolute_error(y_test,y_pred)

1.162540206696516

In [61]:
np.sqrt(mean_squared_error(y_test,y_pred))

1.605799802068275

In [62]:
y_test.mean()

Sales    13.61
dtype: float64

In [63]:
# Create Linear Regression with ElasticNet
elastic = ElasticNetCV(alphas=None,cv=10)
elastic.fit(x_train,y_train)

D:\ANACONDA\anaconda3\Lib\site-packages\sklearn\linear_model\_coordinate_descent.py:1563: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


ElasticNetCV(cv=10)

In [64]:
elastic.alpha_

0.008949991971088199

In [65]:
elastic.l1_ratio_

0.5

In [66]:
elastic_lr=ElasticNet(alpha=elastic.alpha_,l1_ratio=elastic.l1_ratio_)
elastic_lr.fit(x_train,y_train)

ElasticNet(alpha=0.008949991971088199)

In [67]:
elastic_lr.score(x_test,y_test)

0.9086526410018507